<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_katalon studio tutorial</name>
   <tag></tag>
   <elementGuidId>00598d7d-b742-4071-97cd-1395dc64bf2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ERWdKc > div.wM6W7d > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ERWdKc']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7623780e-a93f-451c-bdf7-8a739c427ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>katalon studio tutorial</value>
      <webElementGuid>23c867de-94f9-492a-a837-0ce9db336f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ERWdKc&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>8632d07d-4b06-4f06-8900-b21a3c3796e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ERWdKc']/div/span</value>
      <webElementGuid>497352f3-5119-4f68-82a5-9267f65eca5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::span[1]</value>
      <webElementGuid>cfda6842-3926-4206-a403-9ade2a79d5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[1]/following::span[2]</value>
      <webElementGuid>756436eb-b5b7-4c77-9ec9-1d7101b569a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='British actress'])[1]/preceding::span[1]</value>
      <webElementGuid>567bef5a-2d8d-4194-a66b-0b3aca9d2703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/li[2]/div/div[2]/div/div/span</value>
      <webElementGuid>49649a5c-0003-4dc2-8131-af2182c9e96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'katalon studio tutorial' or . = 'katalon studio tutorial')]</value>
      <webElementGuid>1c77a074-3eac-4ac6-8618-e16511239f8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
