<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Demo</name>
   <tag></tag>
   <elementGuidId>137d033b-154a-4da0-9e32-89c825cad6a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.JQ18Hc.MUxGbd.v0nnCb.lyLwlc.aLF0Z.OSrXXb > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3edb0d86-d331-4260-ac60-7a720b3f83d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agch</name>
      <type>Main</type>
      <value>HJ3bqe</value>
      <webElementGuid>a8cddbe1-8aea-4a4f-b828-797845af8115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-impdclcc</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>fb11ccf3-1453-4342-9df1-7de80ad83bd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agdh</name>
      <type>Main</type>
      <value>fvd3vc</value>
      <webElementGuid>5144a5fc-4766-41c9-9c1a-140786cafdcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rw</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwi83dLJrIiAAxWHupYKHelID48YABABGgJ0bA&amp;ohost=www.google.com&amp;cid=CAASJeRoOk3iL_HjVCqOFNVHV-6WQXnHEctqa1Al6fBxOHxTp7_4KA8&amp;sig=AOD64_2UZnrWm3OGaoDnyv9L7PFWi1nNfA&amp;adurl</value>
      <webElementGuid>aa41882a-d714-409a-ba29-3c1635d14663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwi83dLJrIiAAxWHupYKHelID48YABABGgJ0bA&amp;ohost=www.google.com&amp;cid=CAASJeRoOk3iL_HjVCqOFNVHV-6WQXnHEctqa1Al6fBxOHxTp7_4KA8&amp;sig=AOD64_2UZnrWm3OGaoDnyv9L7PFWi1nNfA&amp;adurl&amp;ved=2ahUKEwj17c3JrIiAAxWTZvUHHbJhAMcQqyQoAHoECAcQCw</value>
      <webElementGuid>92dec595-8a95-48b9-b1e1-86905834b057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ae</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f342d764-9a85-4ee3-b33a-b9d1d2f8579b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-al</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2740e2bf-8498-46d8-a25e-0f02c05c4226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ACyKwe</value>
      <webElementGuid>d6f46fbd-e97a-4d2d-928b-4bc73f0084e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwj17c3JrIiAAxWTZvUHHbJhAMcQqyQoAHoECAcQCw</value>
      <webElementGuid>dac88d38-9a10-4a25-b8ca-b7b83c4ff782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Demo</value>
      <webElementGuid>e38eb378-e46c-47e8-a09e-de26ead39dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tads&quot;)/div[@class=&quot;uEierd&quot;]/div[1]/div[1]/div[@class=&quot;vdQmEd fP1Qef EtOod pkphOe&quot;]/div[@class=&quot;UBEOKe&quot;]/div[@class=&quot;MhgNwc&quot;]/h3[1]/div[@class=&quot;JQ18Hc MUxGbd v0nnCb lyLwlc aLF0Z OSrXXb&quot;]/a[1]</value>
      <webElementGuid>a9f57997-e4e3-40db-a0ae-8395b5891018</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      <webElementGuid>a380347b-d2b5-4ec1-b6cf-8226f1041688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Demo')]</value>
      <webElementGuid>8db6c1c0-feb3-4680-94d4-819fb955c186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutorials'])[1]/following::a[1]</value>
      <webElementGuid>e6d3f543-8b0d-43ae-ba1e-cbc3860d6671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Ad Centre'])[1]/following::a[1]</value>
      <webElementGuid>00f8c672-9440-4b34-b24b-c084f44f49eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule A Live Demo. Meet 1-on-1 with Katalon experts.'])[1]/preceding::a[1]</value>
      <webElementGuid>9f1cf144-b0b2-4be7-840c-edb9b82f5fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon?'])[1]/preceding::a[1]</value>
      <webElementGuid>c907be2e-b3c4-47e5-b01f-a6e775c0df2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Demo']/parent::*</value>
      <webElementGuid>fd9f15b9-0159-4aaf-ac33-e14461a125e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwi83dLJrIiAAxWHupYKHelID48YABABGgJ0bA&amp;ohost=www.google.com&amp;cid=CAASJeRoOk3iL_HjVCqOFNVHV-6WQXnHEctqa1Al6fBxOHxTp7_4KA8&amp;sig=AOD64_2UZnrWm3OGaoDnyv9L7PFWi1nNfA&amp;adurl&amp;ved=2ahUKEwj17c3JrIiAAxWTZvUHHbJhAMcQqyQoAHoECAcQCw')]</value>
      <webElementGuid>4ca30f86-1336-4a8f-916e-47653ead72b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/a</value>
      <webElementGuid>d985c2db-df18-4d6b-bd3e-acb0b918ec47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwi83dLJrIiAAxWHupYKHelID48YABABGgJ0bA&amp;ohost=www.google.com&amp;cid=CAASJeRoOk3iL_HjVCqOFNVHV-6WQXnHEctqa1Al6fBxOHxTp7_4KA8&amp;sig=AOD64_2UZnrWm3OGaoDnyv9L7PFWi1nNfA&amp;adurl&amp;ved=2ahUKEwj17c3JrIiAAxWTZvUHHbJhAMcQqyQoAHoECAcQCw' and (text() = 'View Demo' or . = 'View Demo')]</value>
      <webElementGuid>097cf5a9-225d-4c34-86ae-6f377e8d465b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
