<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_katalon studio tutorial</name>
   <tag></tag>
   <elementGuidId>dacfd082-e6f2-4aeb-9971-38d86eb55eb5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#sBQTL > div.wM6W7d > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sBQTL']/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>422e7c21-23f0-4647-94a9-7bca198ef959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>katalon studio tutorial</value>
      <webElementGuid>1c07bb13-c393-4081-874e-3aad6076ab15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sBQTL&quot;)/div[@class=&quot;wM6W7d&quot;]/span[1]</value>
      <webElementGuid>2662386e-2302-4a85-af33-ffd1753d5fbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sBQTL']/div/span</value>
      <webElementGuid>a55528bd-d3f6-4c0c-876b-42b4466f36d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[4]/following::span[1]</value>
      <webElementGuid>b5a22484-f482-4549-a2d6-654239410bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='See more'])[4]/following::span[2]</value>
      <webElementGuid>7a1934eb-dc2a-4ee0-8532-948169617700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video game'])[1]/preceding::span[1]</value>
      <webElementGuid>9808ab05-4a18-4ab2-88d2-b8adda2a8629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div[2]/div/div/span</value>
      <webElementGuid>44b0a9e5-9434-4856-ba88-7d62762d7741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'katalon studio tutorial' or . = 'katalon studio tutorial')]</value>
      <webElementGuid>fd7a733d-06db-4e7e-b7d2-27908112df5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
