<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View Demo</name>
   <tag></tag>
   <elementGuidId>00918e4f-c0bd-490c-a434-d35bc17cb729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.JQ18Hc.MUxGbd.v0nnCb.lyLwlc.aLF0Z.OSrXXb > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38f41fd7-8b6b-4b3e-92ad-d77584f11a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agch</name>
      <type>Main</type>
      <value>HJ3bqe</value>
      <webElementGuid>296673a4-9f60-4718-9ac8-64952a34fccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-impdclcc</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5c8a99c2-4366-4fc2-89ab-634a5aa61ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agdh</name>
      <type>Main</type>
      <value>fvd3vc</value>
      <webElementGuid>4b327bdd-8995-4518-ab46-3df2adc26486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rw</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwjF88a9soiAAxVo2EwCHa3ZAHEYABACGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJeRonBjV_Qc9QKIMJVIRaOoTUixdHblFZ5oYiKDHe7LQp3G1_5Q&amp;sig=AOD64_0Ob-xlvVl_M0lwXT2q62aDqHI_0Q&amp;adurl</value>
      <webElementGuid>be328f00-3802-4957-bef7-a2ae48f7d0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwjF88a9soiAAxVo2EwCHa3ZAHEYABACGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJeRonBjV_Qc9QKIMJVIRaOoTUixdHblFZ5oYiKDHe7LQp3G1_5Q&amp;sig=AOD64_0Ob-xlvVl_M0lwXT2q62aDqHI_0Q&amp;adurl&amp;ved=2ahUKEwiDqsG9soiAAxXoUPUHHZjMCg4QqyQoAHoECAcQCw</value>
      <webElementGuid>979151ed-aec2-47d9-b9d0-91e05a9b7126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ae</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>54c97eb9-ede2-4fc6-8568-cd09115f6ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-al</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3a946555-cc34-4568-8d45-012c95a57290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ACyKwe</value>
      <webElementGuid>f39facc7-5cfb-4b2c-9091-e478b2aca528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwiDqsG9soiAAxXoUPUHHZjMCg4QqyQoAHoECAcQCw</value>
      <webElementGuid>a620d977-7e31-4ef8-bc9b-734dd906b301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Demo</value>
      <webElementGuid>d1951ae6-fc24-4205-a907-78a214037a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tads&quot;)/div[@class=&quot;uEierd&quot;]/div[1]/div[1]/div[@class=&quot;vdQmEd fP1Qef EtOod pkphOe&quot;]/div[@class=&quot;UBEOKe&quot;]/div[@class=&quot;MhgNwc&quot;]/h3[1]/div[@class=&quot;JQ18Hc MUxGbd v0nnCb lyLwlc aLF0Z OSrXXb&quot;]/a[1]</value>
      <webElementGuid>931c2aa8-93b6-43df-ac2e-b86e367b5403</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      <webElementGuid>97e297f1-619c-4628-9061-c6f40e684319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'View Demo')]</value>
      <webElementGuid>c3702ab3-c7a3-4fd5-bc68-d52ecaa80abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutorials'])[1]/following::a[1]</value>
      <webElementGuid>b6e3ca4a-22c0-4413-9d33-c1778303e891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Ad Centre'])[1]/following::a[1]</value>
      <webElementGuid>4d17c946-7f4e-42dc-9c59-0b992dff552d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule A Live Demo. Meet 1-on-1 with Katalon experts.'])[1]/preceding::a[1]</value>
      <webElementGuid>5289a6fb-a918-472d-bf5f-0abb2ab31c61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Katalon?'])[1]/preceding::a[1]</value>
      <webElementGuid>a4daac33-3411-46b5-b66c-ec4cbbfd4090</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='View Demo']/parent::*</value>
      <webElementGuid>f6a92dba-4fc4-47ee-938b-187125088b09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwjF88a9soiAAxVo2EwCHa3ZAHEYABACGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJeRonBjV_Qc9QKIMJVIRaOoTUixdHblFZ5oYiKDHe7LQp3G1_5Q&amp;sig=AOD64_0Ob-xlvVl_M0lwXT2q62aDqHI_0Q&amp;adurl&amp;ved=2ahUKEwiDqsG9soiAAxXoUPUHHZjMCg4QqyQoAHoECAcQCw')]</value>
      <webElementGuid>c37403bd-b27a-48d8-ad71-ebba8c4bada3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/a</value>
      <webElementGuid>8b99c81f-aa56-47d2-a62b-d1656843f859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwjF88a9soiAAxVo2EwCHa3ZAHEYABACGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJeRonBjV_Qc9QKIMJVIRaOoTUixdHblFZ5oYiKDHe7LQp3G1_5Q&amp;sig=AOD64_0Ob-xlvVl_M0lwXT2q62aDqHI_0Q&amp;adurl&amp;ved=2ahUKEwiDqsG9soiAAxXoUPUHHZjMCg4QqyQoAHoECAcQCw' and (text() = 'View Demo' or . = 'View Demo')]</value>
      <webElementGuid>eaaa6a83-1d26-4170-8bf9-f559d18a6a52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
