<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sub Total 58.79_updateCartQuantities</name>
   <tag></tag>
   <elementGuidId>3164245a-dcd8-4bbf-84ee-c253e8e86a52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;updateCartQuantities&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='updateCartQuantities']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd8e3f04-7963-43f3-bd8e-fc598474fef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updateCartQuantities</value>
      <webElementGuid>12b8aa38-a8ba-4de4-9b46-8837c3707381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6bfa92a4-03dc-4fe5-811c-12a07f135a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Update Cart</value>
      <webElementGuid>b57e78f2-0e3b-4f7b-8298-c359a1f56ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[6]/td[1]/input[1]</value>
      <webElementGuid>5129f451-104b-44a5-a6a9-33bab204eb1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='updateCartQuantities']</value>
      <webElementGuid>23f4bbbe-5478-413c-a574-401e4691aefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[6]/td/input</value>
      <webElementGuid>9a7f9835-fe57-4d9c-a644-2bb7a0cf4d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>7d2e56aa-32ab-4bc4-97e9-0c2c4081ac6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'updateCartQuantities' and @type = 'submit']</value>
      <webElementGuid>b3c5f4a8-5d5f-4b30-a609-b6a58b02d545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
