<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Submit_popup_back</name>
   <tag></tag>
   <elementGuidId>b69d56de-3f15-4919-bea3-8545e8597623</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popup_back</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-get-a-demo-submit']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>78ecd635-1e43-440b-8bc7-688fb7dbff28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup_back</value>
      <webElementGuid>f0d4b63c-a67d-488e-8fd5-068affd37508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-get-a-demo-submit&quot;)/div[@class=&quot;popup_back&quot;]</value>
      <webElementGuid>a3a0be48-1844-4cde-a698-b7ebd0753ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-get-a-demo-submit']/div[2]</value>
      <webElementGuid>a547d8bf-158f-4b24-9284-e58118ab6c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]</value>
      <webElementGuid>1c319658-25d3-44ed-9b1f-94e3893c1e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
