<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Out-of-the-box fit for any ALM, CI tool_b38796</name>
   <tag></tag>
   <elementGuidId>1505514e-c445-41bf-8d9e-ef07fd33504a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wistia_87.big_play_button_graphic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ed5136b-1e5f-4b7f-a2f6-7ea8090b1bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wistia_87.big_play_button_graphic</value>
      <webElementGuid>f57600c2-c370-4584-a9f9-1cb1b3eae0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>59757b74-bcc7-4073-a317-a4c5eff7b214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>942e53e1-07b3-4f96-8ddc-2ea674df76fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>fa7a7379-572c-4b8c-a568-e4553205b356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wistia_mouseover wistia_focus</value>
      <webElementGuid>d6e04f8d-723e-403f-bbb3-a28fbe4b8aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wistia_87.big_play_button_graphic&quot;)</value>
      <webElementGuid>9e696de9-3b95-4b21-87de-9deb08540f00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wistia_87.big_play_button_graphic']</value>
      <webElementGuid>3cbd2712-2080-494f-aca6-467879d566fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wistia_71.thumbnail']/div[3]</value>
      <webElementGuid>9df6ee53-ca14-47b4-8e60-24704020b233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div[3]</value>
      <webElementGuid>beadcdd3-1a9f-49cd-b502-d4bcb6ae3f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wistia_87.big_play_button_graphic']</value>
      <webElementGuid>3ae2a8a6-8ddc-4b83-80f0-b53de80e0f59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
