<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_false_EST-11</name>
   <tag></tag>
   <elementGuidId>d4a9a466-b42e-4531-b251-947f6f52c3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;EST-11&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='EST-11']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c56328b9-72d5-4a39-aa50-3e6e25cfa98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8a988776-9a44-4abb-9f1c-2820f6e974df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EST-11</value>
      <webElementGuid>8a7e7880-294b-4a7a-8ce7-523a5ff5e01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f20cb86-093f-477b-a369-e20e17f57e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a01af4b3-eb66-4023-98b4-1b0cf02d7c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Cart&quot;)/form[1]/table[1]/tbody[1]/tr[4]/td[5]/input[1]</value>
      <webElementGuid>9d838d44-b9ca-41be-87f3-cc380416c73e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='EST-11']</value>
      <webElementGuid>d1945a8d-0d8b-4aae-8670-9e5fdf894cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Cart']/form/table/tbody/tr[4]/td[5]/input</value>
      <webElementGuid>2bf8a543-787d-4359-8d08-b2517d454a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[5]/input</value>
      <webElementGuid>50629eed-af9d-4910-a4a2-4f156c3e5e1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EST-11' and @type = 'text']</value>
      <webElementGuid>ed88cd46-6a29-405c-a995-61c52178efb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
