<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Katalon Academy</name>
   <tag></tag>
   <elementGuidId>56d9094e-7c39-43d9-89e1-31dd0af37026</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.JQ18Hc.MUxGbd.v0nnCb.lyLwlc.aLF0Z.OSrXXb > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>89b21ec8-967b-4c96-bf71-659094e6fc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agch</name>
      <type>Main</type>
      <value>HJ3bqe</value>
      <webElementGuid>7b1e8221-1049-40f4-89f8-9a6d46ed58ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-impdclcc</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3478a8a8-5e43-481f-ac52-a998414e4ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-agdh</name>
      <type>Main</type>
      <value>fvd3vc</value>
      <webElementGuid>6c307bb0-c8a6-4e08-b7aa-3fb17143104c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rw</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwj6sufhgfz_AhWIisIKHVmBAqcYABABGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJuRoGBYD3EBf1UMHQms9TmQJe9fQrnTLUpx5zkw7cGJpXy0KU18A&amp;sig=AOD64_1YO2yn3duPbbZRR8a1H2VApT9kcg&amp;adurl</value>
      <webElementGuid>962fca3c-da82-4797-86c3-5b25437971ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwj6sufhgfz_AhWIisIKHVmBAqcYABABGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJuRoGBYD3EBf1UMHQms9TmQJe9fQrnTLUpx5zkw7cGJpXy0KU18A&amp;sig=AOD64_1YO2yn3duPbbZRR8a1H2VApT9kcg&amp;adurl&amp;ved=2ahUKEwi7rOLhgfz_AhWDRN4KHZhhBD8QqyQoAHoECAMQCw</value>
      <webElementGuid>ed283655-7760-4c50-8be1-631e15b40ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ae</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>780cc77d-8b4a-4b7d-8798-041a35a5f485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-al</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b21448b9-e5c2-48df-a5eb-6b46c09e4439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>ACyKwe</value>
      <webElementGuid>1848e164-3b77-455c-b9ea-5285fa04fe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>2ahUKEwi7rOLhgfz_AhWDRN4KHZhhBD8QqyQoAHoECAMQCw</value>
      <webElementGuid>0d9485c5-6024-40e1-9049-cdaeda651b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Katalon Academy</value>
      <webElementGuid>5f7afe42-e9dd-4584-b862-dedf8f1cce38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tads&quot;)/div[@class=&quot;uEierd&quot;]/div[1]/div[1]/div[@class=&quot;vdQmEd fP1Qef EtOod pkphOe&quot;]/div[@class=&quot;UBEOKe&quot;]/div[@class=&quot;MhgNwc&quot;]/h3[1]/div[@class=&quot;JQ18Hc MUxGbd v0nnCb lyLwlc aLF0Z OSrXXb&quot;]/a[1]</value>
      <webElementGuid>68cc5a22-bacc-4b61-a40d-744221e5ef73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tads']/div/div/div/div/div[3]/div/h3/div/a</value>
      <webElementGuid>1d987978-f773-4f4b-a58c-a1ec639a6a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Katalon Academy')]</value>
      <webElementGuid>79fe0c63-d112-4cac-bf84-9960970c3139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tutorials'])[1]/following::a[1]</value>
      <webElementGuid>fbdde8ed-cbb6-4622-a732-723e0bf18ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Ad Centre'])[1]/following::a[1]</value>
      <webElementGuid>39652791-891a-4cf2-8954-95615f5afd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn automation from professionals Enroll for free.'])[1]/preceding::a[1]</value>
      <webElementGuid>816ceb70-9e4c-40b7-a572-9b4896c6d8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Demo'])[1]/preceding::a[1]</value>
      <webElementGuid>693c2d7c-2f50-4871-aca8-f674cbf89210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Katalon Academy']/parent::*</value>
      <webElementGuid>f6b01b53-fe32-45ba-830d-8f599a714548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwj6sufhgfz_AhWIisIKHVmBAqcYABABGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJuRoGBYD3EBf1UMHQms9TmQJe9fQrnTLUpx5zkw7cGJpXy0KU18A&amp;sig=AOD64_1YO2yn3duPbbZRR8a1H2VApT9kcg&amp;adurl&amp;ved=2ahUKEwi7rOLhgfz_AhWDRN4KHZhhBD8QqyQoAHoECAMQCw')]</value>
      <webElementGuid>1e9ae7d0-0d27-4304-bfe1-be5ae24b42d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/div/a</value>
      <webElementGuid>671cc5ba-99cb-4801-8945-5dbafa66215a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.googleadservices.com/pagead/aclk?sa=L&amp;ai=DChcSEwj6sufhgfz_AhWIisIKHVmBAqcYABABGgJ0bQ&amp;ohost=www.google.com&amp;cid=CAASJuRoGBYD3EBf1UMHQms9TmQJe9fQrnTLUpx5zkw7cGJpXy0KU18A&amp;sig=AOD64_1YO2yn3duPbbZRR8a1H2VApT9kcg&amp;adurl&amp;ved=2ahUKEwi7rOLhgfz_AhWDRN4KHZhhBD8QqyQoAHoECAMQCw' and (text() = 'Katalon Academy' or . = 'Katalon Academy')]</value>
      <webElementGuid>06b6770d-753c-4022-aa26-8769b311eea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
