<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_x</name>
   <tag></tag>
   <elementGuidId>89f08a7b-f3cd-4258-beb1-87bb22354cd2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.close-popup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='close-popup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1a85a31b-a0a7-4a99-b5df-3274697d446a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-popup</value>
      <webElementGuid>24c0973c-3233-45a4-95e6-64ecba7b24aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>x</value>
      <webElementGuid>abadbd99-09bf-4e63-bbc3-f048fbfe2d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-get-a-demo-submit&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;close-popup&quot;]</value>
      <webElementGuid>2cbedd23-ff73-4fc9-bc14-775848d041e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-get-a-demo-submit']/div/div/div/div</value>
      <webElementGuid>c76a49bf-bbef-4a4f-b285-0ae4589ab264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All jobs'])[2]/following::div[6]</value>
      <webElementGuid>0d394924-6a75-425b-84fb-17ae3c84a87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being here'])[2]/following::div[6]</value>
      <webElementGuid>df28f6b8-6da5-469b-8bd0-17e84f8aa7c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Want to book a personalized demo with one of our product experts?'])[1]/preceding::div[1]</value>
      <webElementGuid>e2d84573-671a-4895-ba97-dabb6b41806e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[2]</value>
      <webElementGuid>15eca5dd-3c5c-4c5e-8803-1f804a4fbf8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='x']/parent::*</value>
      <webElementGuid>a3d10a45-15e8-4f25-8b0e-b8928a4d0d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div</value>
      <webElementGuid>976eb75f-7452-475f-a2c3-5c50c43ad9d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'x' or . = 'x')]</value>
      <webElementGuid>c8d099cb-ee27-463d-84cb-47ddd36f5c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
