<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Out-of-the-box fit for any ALM, CI tool_b38796</name>
   <tag></tag>
   <elementGuidId>bae3f5f8-7f9a-41fd-87b0-a2aa364e10e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wistia_87.big_play_button_graphic']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f9fd032-4056-40fc-bdf9-62fd1209fea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wistia_87.big_play_button_graphic</value>
      <webElementGuid>0ca30b68-cae0-4147-a354-607506275a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>137ec040-ea34-43f5-8956-e7dae006604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac3009c1-c62c-4885-8d8f-0e26d5033642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Play</value>
      <webElementGuid>4ae51972-795d-4a23-830c-4910f0a0cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wistia_mouseover wistia_focus</value>
      <webElementGuid>686032c4-d4e1-4476-9347-44fb8d701c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wistia_87.big_play_button_graphic&quot;)</value>
      <webElementGuid>f57e471e-e963-4787-b3e3-4dfbb2c9fc92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='wistia_87.big_play_button_graphic']</value>
      <webElementGuid>c058b2c1-9e9c-4b65-8711-6828f8c108a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wistia_71.thumbnail']/div[3]</value>
      <webElementGuid>728adad9-d33a-4774-940e-eb7b6f1b47df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div/div[3]</value>
      <webElementGuid>663ce052-dd7e-4c5c-b7c9-c492fa5859e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'wistia_87.big_play_button_graphic']</value>
      <webElementGuid>31513ac7-2f1a-4df8-8770-6c5b37ffe2c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
